### ISSUE TITLE
我遇到的问题

### ISSUE THREAD

**Issue by 237xxx** [linwoodpendleton/gogo2#2]
windows  set to  0
syn/ack  ack   psh/ack   ack fin/ack  ack  window = 0
 windows set to 1
syn/ack  ack   psh/ack     window = 0
ack fin/ack  ack  window = 128

作者遇到过吗?

**Comment by linwoodpendleton** [comment]
windows set to 0
这个就该不能设置为0,至少1吧.
windows set to 1
syn/ack ack psh/ack window = 0
ack fin/ack ack window = 128

如果是本机发送时就这样.那链路有问题
如果接收是这样.就是上级路由我拆分合并.

**Comment by 237xxx** [comment]
为啥不能设置为0?  设置为0  , server 发出的消息 都是window 为0 , wireshark 提示 tcp zerowindow

**Comment by 237xxx** [comment]
只为了跳转用,不在这个IP后续有通信

**Comment by 237xxx** [comment]
设置为0 ,  只是为了跳转用, 不在这个ip 接着通信
